version: '2'
services:
  ser:
    build: .
    ports:
     - "8080:80"
    depends_on:
     - solr
    volumes:
     - ./server/public:/var/www/html/
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./data/core:/opt/solr/server/solr/mycores/mycore
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
volumes:
  data:
